server:
  port: 10601
spring:
  application:
    name: spring-cloud-zuul-demo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10101/eureka/
zuul:
  routes:
    api-consumer:
      path: /consumer/**
      serviceId: spring-cloud-consumer-demo
    api-provider:
      path: /provider/**
      serviceId: spring-cloud-provider-demo         
#   max:
#       host:
#         connections: 500
#   host:
#     socket-timeout-millis: 60000
#     connect-timeout-millis: 60000
# hystrix:
#   command:
#     default:
#       execution:
#         timeout:
#           enabled: false
#         isolation:
#           thread:
#             timeoutInMilliseconds: 60000
# ribbon:
#   ReadTimeout: 60000
#   ConnectTimeout: 60000