server:
  port: 10401
spring:
  application:
    name: spring-cloud-middle-demo
  zipkin:
    service:
      name: ${spring.application.name}
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10101/eureka/
# feign:
#   hystrix:
#     enabled: true