spring:
  application:
    name: spring-cloud-consumer-demo
  profiles:
    active: server1
  zipkin:
    service:
      name: ${spring.application.name}
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
feign:
  hystrix:
    enabled: true
