server:
  port: 9411
spring:
  application:
    name: zipkin-server
zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
      hosts: localhost:9300
      index: zipkin
  collector:
   #rabbitmq:
      #addresses: localhost:5672
      ##password: guest
      ##username: guest
      #queue: zipkin
    kafka:
      zookeeper: localhost:2181
      topic: zipkin
      groupId: zipkin
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/