server:
  port: 9411
spring:
  application:
    name: zipkin-server
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: localhost:9200
      index: zipkin
  collector:
   #rabbitmq:
      #addresses: localhost:5672
      ##password: guest
      ##username: guest
      #queue: zipkin
    kafka:
      bootstrap-servers: localhost:9092
      topic: zipkin
      groupId: zipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/