server:
  port: 10301
spring:
  application:
    name: spring-cloud-consumer-demo
  zipkin:
    sender:
      type: kafka
    # base-url: http://localhost:9411
    kafka:
      topic: zipkin
      # group-id: zipkin
  sleuth:
    sampler:
      percentage: 1.0
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10101/eureka/
feign:
  hystrix:
    enabled: true
