server:
  port: 10301
# https://docs.spring.io/spring-boot/docs/2.0.3.RELEASE/reference/html/common-application-properties.html
  tomcat: 
    max-threads: 5
spring:
  application:
    name: spring-cloud-consumer-demo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10101/eureka/, http://localhost:10102/eureka/
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
#   hystrix:
#     enabled: true
# ribbon:
#   ReadTimeout: 100000
#   ConnectTimeout: 10000
# hystrix:
#   command:
#     default:
#       execution:
#         timeout:
#           enabled: false