server:
  port: 10301
spring:
  application:
    name: spring-cloud-consumer-demo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10101/eureka/
feign:
  hystrix:
    enabled: true
