server:
  port: 10301
spring:
  zipkin:
    sender:
      type: kafka
    # base-url: http://localhost:9411
    kafka:
      topic: zipkin
      # group-id: zipkin
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: 127.0.0.1:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10101/eureka/
feign:
  hystrix:
    enabled: true

logging.level.org.springframework.cloud.sleuth: DEBUG
#management.endpoints.web.base-path: /
management.endpoints.web.exposure.include: "*"
management.metrics.export.atlas:
  uri: http://localhost:7101/api/v1/publish

