debug: true
server:
  port: 10101
spring.security.user:
  name: abc
  password: abcabc
  roles: user
eureka:
  server:
    renewalPercentThreshold: 0.3
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://abc:abcabc@localhost:10101/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/