server:
  port: 10201
spring:
  application:
    name: spring-cloud-provider-demo
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:10101/eureka