server:
  port: 10201
spring:
  application:
    name: spring-cloud-provider-demo
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:10101/eureka
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#App Configuration:
app:
  config: 
    delay: 20