server:
  port: 10201
spring:
  application:
    name: spring-cloud-provider-demo
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.230.171.89:10101/eureka
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
#App Configuration:
app:
  config: 
    delay: 20