server:
  port: 10201
spring:
  application:
    name: spring-cloud-provider-demo
  zipkin:
    service:
      name: ${spring.application.name}
    #base-url: http://localhost:9411
    sender:
      type: kafka
    kafka:
      topic: zipkin
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: 127.0.0.1:9092

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:10101/eureka
      
management.endpoints.web.exposure.include: "*"
#App Configuration:
app:
  config: 
    delay: 0
    error: false
