server:
  port: 10201
spring:
  application:
    name: spring-cloud-provider-demo
  zipkin:
    service:
      name: ${spring.application.name}
    #base-url: http://localhost:9411
    sender:
      type: kafka
    kafka:
      topic: zipkin
  sleuth:
    sampler:
      percentage: 1.0
  kafka:
    bootstrap-servers: localhost:9092
  
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:10101/eureka
#App Configuration:
app:
  config: 
    delay: 0
    error: false