server:
  port: 10202
eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      zone: beijing-2
  client:
    prefer-same-zone-eureka: true
    #地区
    region: beijing
    availability-zones:
      beijing: beijing-1,beijing-2
    service-url:
      beijing-1: http://localhost:10101/eureka/
      beijing-2: http://localhost:10103/eureka/