spring:
  application:
    name: spring-cloud-provider-demo
  profiles:
    active: server1
  zipkin:
    service:
      name: ${spring.application.name}
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
#App Configuration:
app:
  config: 
    delay: 0
    error: false