server:
  port: 10201
spring:
  application:
    name: spring-cloud-provider-demo
  zipkin:
    service:
      name: ${spring.application.name}
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:10101/eureka,http://localhost:10102/eureka
#App Configuration:
app:
  config: 
    delay: 0
    error: false